<?php

namespace App\Http\Controllers;

use App\Helpers\ResponseHelper;
use App\Http\Requests\StoreStoreRequest;
use App\Http\Requests\StoreUpdateRequest;
use App\Http\Resources\PaginatedResource;
use App\Http\Resources\StoreResource;
use App\Interface\StoreRepositoryInterface;
use Illuminate\Http\Request;

class StoreController extends Controller
{
    private StoreRepositoryInterface $storeRepository;

    public function __construct(StoreRepositoryInterface $storeRepository)
    {
        $this->storeRepository = $storeRepository;
    }

    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $request->validate([
            'search' => 'nullable|string',
            'is_verified' => 'nullable|boolean',
            'limit' => 'nullable|integer',
        ]);
        try {
            $store = $this->storeRepository->getAllPaginated(
                $request->search,
                $request->is_verified,
                $request->limit,
                true
            );

            return ResponseHelper::jsonResponse(true, 'Data User', StoreResource::collection($store), 200);
        } catch (\Exception $e) {
            return ResponseHelper::jsonResponse(false, $e->getMessage(), null, 500);
        }
    }

    public function getAllPaginated(Request $request)
    {
        $request->validate([
            'search' => 'nullable|string',
            'is_verified' => 'nullable|boolean',
            'row_per_page' => 'required|integer',
        ]);

        try {
            $store = $this->storeRepository->getAllPaginated(
                $request->search,
                $request->is_verified,
                $request->row_per_page,
                false
            );

            return ResponseHelper::jsonResponse(true, 'Data User', PaginatedResource::make($store, StoreResource::class), 200);
        } catch (\Exception $e) {
            return ResponseHelper::jsonResponse(false, $e->getMessage(), null, 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreStoreRequest $request)
    {
        $request = $request->validated();
        try {
            $store = $this->storeRepository->create($request);

            return ResponseHelper::jsonResponse(true, 'Data User', new StoreResource($store), 201);
        } catch (\Throwable $e) {
            return ResponseHelper::jsonResponse(false, $e->getMessage(), null, 500);
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        try {
            $store = $this->storeRepository->getById($id);
            if (! $store) {
                return ResponseHelper::jsonResponse(false, 'Data Store Not Found', null, 404);
            }

            return ResponseHelper::jsonResponse(true, 'Data Store', new StoreResource($store), 200);
        } catch (\Throwable $e) {
            return ResponseHelper::jsonResponse(false, $e->getMessage(), null, 500);
        }
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(StoreUpdateRequest $request, string $id)
    {
        $request = $request->validated();
        try {
            $store = $this->storeRepository->getById($id);
            if (! $store) {
                return ResponseHelper::jsonResponse(false, 'Data Store Not Found', null, 404);
            }

            $store = $this->storeRepository->update($request, $id);

            return ResponseHelper::jsonResponse(true, 'Data Store', new StoreResource($store), 200);
        } catch (\Throwable $e) {
            return ResponseHelper::jsonResponse(false, $e->getMessage(), null, 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        try {
            $store = $this->storeRepository->getById($id);
            if (! $store) {
                return ResponseHelper::jsonResponse(false, 'Data Store Not Found', null, 404);
            }

            $store = $this->storeRepository->delete($id);

            return ResponseHelper::jsonResponse(true, 'Data Store Deleted', null, 200); // TODO: Change the autogenerated stub
        } catch (\Throwable $e) {
            return ResponseHelper::jsonResponse(false, $e->getMessage(), null, 500);
        }
    }

    public function updateVerifiedStatus(string $id)
    {
        // $request = $request->validated();
        try {
            $store = $this->storeRepository->getById($id);
            if (! $store) {
                return ResponseHelper::jsonResponse(false, 'Data Store Not Found', null, 404);
            }

            $store = $this->storeRepository->updateVerifiedStatus($id, true);

            return ResponseHelper::jsonResponse(true, 'Data Store Berhasil Diverifikasi', new StoreResource($store), 200);
        } catch (\Throwable $e) {
            return ResponseHelper::jsonResponse(false, $e->getMessage(), null, 500);
        }
    }
}
